# Generated by Django 4.2 on 2025-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city_town_village',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_name',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
