# Generated by Django 4.2 on 2025-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_city_town_village_customuser_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city_town_village',
            field=models.CharField(default='', max_length=100, verbose_name='City/Town/Village'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
