# Generated by Django 4.2 on 2025-03-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='messege',
            new_name='message',
        ),
    ]
